-- 1. Priemerná predpovedaná teplota v čase
SELECT
    d.FULL_DATE,
    AVG(f.AVG_TEMP_F) AS AVG_TEMP_F
FROM DIMENSIONAL.FACT_WEATHER_DAY f
JOIN DIMENSIONAL.DIM_DATE d
    ON f.DATE_KEY = d.DATE_KEY
GROUP BY d.FULL_DATE
ORDER BY d.FULL_DATE;

-- 2. Top 15 miest podľa priemernej predpovedanej teploty
SELECT
    l.CITY_NAME,
    AVG(f.AVG_TEMP_F) AS AVG_TEMP_F
FROM DIMENSIONAL.FACT_WEATHER_DAY f
JOIN DIMENSIONAL.DIM_LOCATION l
  ON f.LOCATION_KEY = l.LOCATION_KEY
GROUP BY l.CITY_NAME
ORDER BY AVG_TEMP_F DESC
LIMIT 15;

-- 3. Priemerná teplota podľa typu zrážok
SELECT
    PRECIPITATION_TYPE,
    AVG(AVG_TEMP_F) AS AVG_TEMP_F
FROM DIMENSIONAL.FACT_WEATHER_DAY
GROUP BY PRECIPITATION_TYPE
ORDER BY AVG_TEMP_F DESC;

-- 4. Rozdelenie predpovedí podľa teplotného pásma
SELECT
    WEATHER_BAND,
    COUNT(*) AS DAYS_COUNT
FROM DIMENSIONAL.FACT_WEATHER_DAY
GROUP BY WEATHER_BAND
ORDER BY DAYS_COUNT DESC;

-- 5. Percento lokalít s očakávaným dažďom v čase
SELECT
    DATE_KEY,
    COUNT_IF(PRECIPITATION_IN > 0) * 100.0 / COUNT(*) 
        AS PCT_LOCATIONS_WITH_RAIN
FROM DIMENSIONAL.FACT_WEATHER_DAY
GROUP BY DATE_KEY
ORDER BY DATE_KEY;