-- Vytvorenie samostatnej databázy pre projekt
CREATE OR REPLACE DATABASE PEACOCK_GIRAFFE_PROJECT_DB;

-- Nastavenie kontextu – všetky ďalšie objekty pôjdu sem 
USE DATABASE PEACOCK_GIRAFFE_PROJECT_DB;

-- STAGING – surové dáta zo zdroja (Extract) 
CREATE OR REPLACE SCHEMA STAGING;

-- DIMENSIONAL – dátový sklad (Star Schema) 
CREATE OR REPLACE SCHEMA DIMENSIONAL;

-- NORMALIZED – normalizovaný model pre ERD pôvodnej štruktúry 
CREATE OR REPLACE SCHEMA NORMALIZED;

-- 1. EXTRACT – NAČÍTANIE DÁT Z SNOWFLAKE MARKETPLACE
CREATE OR REPLACE TABLE STAGING.STG_FORECAST_DAY AS
SELECT *
FROM WEATHER_SOURCE_LLC_FROSTBYTE.ONPOINT_ID.FORECAST_DAY;

-- 2. TRANSFORM – DIMENZIE
-- DIM_DATE (časová dimenzia)
CREATE OR REPLACE TABLE DIMENSIONAL.DIM_DATE AS
SELECT DISTINCT
    DATE_VALID_STD              AS DATE_KEY,      -- primárny kľúč dimenzie
    DATE_VALID_STD              AS FULL_DATE,
    YEAR(DATE_VALID_STD)        AS YEAR,
    MONTH(DATE_VALID_STD)       AS MONTH,
    DAY(DATE_VALID_STD)         AS DAY,
    DAYOFWEEKISO(DATE_VALID_STD) AS DAY_OF_WEEK,
    WEEKISO(DATE_VALID_STD)     AS WEEK_OF_YEAR,
    DOY_STD                     AS DAY_OF_YEAR
FROM STAGING.STG_FORECAST_DAY;

-- DIM_LOCATION (lokalita)
CREATE OR REPLACE TABLE DIMENSIONAL.DIM_LOCATION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY POSTAL_CODE, CITY_NAME, COUNTRY)
        AS LOCATION_KEY,          -- surrogate key
    POSTAL_CODE,
    CITY_NAME,
    COUNTRY,
    CURRENT_DATE() AS VALID_FROM, -- začiatok platnosti
    NULL           AS VALID_TO,   -- koniec platnosti
    TRUE           AS IS_CURRENT  -- aktuálny záznam
FROM (
    SELECT DISTINCT
        POSTAL_CODE,
        CITY_NAME,
        COUNTRY
    FROM STAGING.STG_FORECAST_DAY
);

-- DIM_WEATHER_BAND (teplotné pásma)
CREATE OR REPLACE TABLE DIMENSIONAL.DIM_WEATHER_BAND AS
SELECT DISTINCT
    CASE
        WHEN AVG_TEMPERATURE_AIR_2M_F < 32 THEN 'Freezing'
        WHEN AVG_TEMPERATURE_AIR_2M_F BETWEEN 32 AND 50 THEN 'Cold'
        WHEN AVG_TEMPERATURE_AIR_2M_F BETWEEN 51 AND 70 THEN 'Mild'
        WHEN AVG_TEMPERATURE_AIR_2M_F BETWEEN 71 AND 85 THEN 'Warm'
        ELSE 'Hot'
    END AS WEATHER_BAND
FROM STAGING.STG_FORECAST_DAY;

-- DIM_PRECIPITATION_TYPE (typ zrážok)
CREATE OR REPLACE TABLE DIMENSIONAL.DIM_PRECIPITATION_TYPE AS
SELECT DISTINCT
    CASE
        WHEN TOT_SNOWFALL_IN > 0 THEN 'Snow'
        WHEN TOT_PRECIPITATION_IN > 0 THEN 'Rain'
        ELSE 'None'
    END AS PRECIPITATION_TYPE
FROM STAGING.STG_FORECAST_DAY;

-- DIM_SOURCE (zdroj dát)
CREATE OR REPLACE TABLE DIMENSIONAL.DIM_SOURCE AS
SELECT
    1 AS SOURCE_KEY,
    'Weather Source LLC' AS PROVIDER,
    'Frostbyte' AS DATASET_NAME,
    'Snowflake Marketplace' AS INGEST_METHOD;

-- 3. LOAD + TRANSFORM – FAKTOVÁ TABUĽKA
CREATE OR REPLACE TABLE DIMENSIONAL.FACT_WEATHER_DAY AS
SELECT
    d.DATE_KEY,
    l.LOCATION_KEY,
    wb.WEATHER_BAND,
    pt.PRECIPITATION_TYPE,
    s.SOURCE_KEY,

    -- ZÁKLADNÉ METRIKY 
    f.AVG_TEMPERATURE_AIR_2M_F AS AVG_TEMP_F,
    f.TOT_PRECIPITATION_IN     AS PRECIPITATION_IN,
    f.TOT_SNOWFALL_IN          AS SNOWFALL_IN,

    -- WINDOW FUNCTION 1:
    -- Medzidenná zmena teploty (LAG) */
    f.AVG_TEMPERATURE_AIR_2M_F
      - LAG(f.AVG_TEMPERATURE_AIR_2M_F)
        OVER (PARTITION BY l.LOCATION_KEY ORDER BY d.DATE_KEY)
      AS TEMP_DAY_DELTA,

    -- WINDOW FUNCTION 2:
    -- 7-dňový kumulatívny úhrn zrážok */
    SUM(f.TOT_PRECIPITATION_IN)
        OVER (PARTITION BY l.LOCATION_KEY
              ORDER BY d.DATE_KEY
              ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
      AS PRECIPITATION_7D_SUM

FROM STAGING.STG_FORECAST_DAY f
JOIN DIMENSIONAL.DIM_DATE d
    ON f.DATE_VALID_STD = d.DATE_KEY
JOIN DIMENSIONAL.DIM_LOCATION l
    ON f.POSTAL_CODE = l.POSTAL_CODE
   AND l.IS_CURRENT = TRUE
JOIN DIMENSIONAL.DIM_WEATHER_BAND wb
    ON wb.WEATHER_BAND =
       CASE
           WHEN f.AVG_TEMPERATURE_AIR_2M_F < 32 THEN 'Freezing'
           WHEN f.AVG_TEMPERATURE_AIR_2M_F BETWEEN 32 AND 50 THEN 'Cold'
           WHEN f.AVG_TEMPERATURE_AIR_2M_F BETWEEN 51 AND 70 THEN 'Mild'
           WHEN f.AVG_TEMPERATURE_AIR_2M_F BETWEEN 71 AND 85 THEN 'Warm'
           ELSE 'Hot'
       END
JOIN DIMENSIONAL.DIM_PRECIPITATION_TYPE pt
    ON pt.PRECIPITATION_TYPE =
       CASE
           WHEN f.TOT_SNOWFALL_IN > 0 THEN 'Snow'
           WHEN f.TOT_PRECIPITATION_IN > 0 THEN 'Rain'
           ELSE 'None'
       END
JOIN DIMENSIONAL.DIM_SOURCE s
    ON s.SOURCE_KEY = 1;

-- 4. NORMALIZED MODEL – ERD PÔVODNÝCH DÁT
-- NORMALIZED.LOCATION – 3NF lokalita 
CREATE OR REPLACE TABLE NORMALIZED.LOCATION AS
SELECT DISTINCT
    POSTAL_CODE,
    CITY_NAME,
    COUNTRY
FROM STAGING.STG_FORECAST_DAY;

-- NORMALIZED.DATE – 3NF čas 
CREATE OR REPLACE TABLE NORMALIZED.DATE AS
SELECT DISTINCT
    DATE_VALID_STD,
    YEAR(DATE_VALID_STD)         AS YEAR,
    MONTH(DATE_VALID_STD)        AS MONTH,
    DAY(DATE_VALID_STD)          AS DAY,
    DOY_STD                      AS DAY_OF_YEAR,
    WEEKISO(DATE_VALID_STD)      AS WEEK_OF_YEAR,
    DAYOFWEEKISO(DATE_VALID_STD) AS DAY_OF_WEEK
FROM STAGING.STG_FORECAST_DAY;

-- NORMALIZED.WEATHER_DAY – merania 
CREATE OR REPLACE TABLE NORMALIZED.WEATHER_DAY AS
SELECT
    DATE_VALID_STD,
    POSTAL_CODE,
    AVG_TEMPERATURE_AIR_2M_F,
    MIN_TEMPERATURE_AIR_2M_F,
    MAX_TEMPERATURE_AIR_2M_F,
    AVG_HUMIDITY_RELATIVE_2M_PCT,
    AVG_PRESSURE_2M_MB,
    AVG_WIND_SPEED_10M_MPH,
    AVG_CLOUD_COVER_TOT_PCT,
    TOT_PRECIPITATION_IN,
    TOT_SNOWFALL_IN,
    PROBABILITY_OF_PRECIPITATION_PCT,
    PROBABILITY_OF_SNOW_PCT
FROM STAGING.STG_FORECAST_DAY;

-- 5. VALIDÁCIA DÁT
-- Kontrola, či fakt nemá chýbajúce cudzie kľúče 
SELECT COUNT(*) 
FROM DIMENSIONAL.FACT_WEATHER_DAY
WHERE LOCATION_KEY IS NULL OR DATE_KEY IS NULL;

-- Kontrola rozsahu teplôt 
SELECT
    MIN(AVG_TEMP_F),
    MAX(AVG_TEMP_F)
FROM DIMENSIONAL.FACT_WEATHER_DAY;

